### ISSUE TITLE
File copy to external causing 

### ISSUE THREAD

**Issue by skyvondave** [PHPIDS/PHPIDS#78]
It's unable to write to the default_filter.cache which for some reason changes user:group to root:root _sometimes_ after I copy over files from my local editor (in Mac) to the external Linux box through FTP (which also changes those files' user:group to root:root even though I set the docroot's files recursively to user lighttpd).

The source code is below (version 0.5.6) and of course the path to it is in the page error below that; I don't know why this is happening or how to prevent any of the files being changed to root user:

```
        if (file_exists($this->path) && !is_writable($this->path)) {
            throw new Exception('Make sure all files in ' . 
            htmlspecialchars($this->path, ENT_QUOTES, 'UTF-8') . 
                'are writeable!');
        }
```

We apologize, but an error occurred while processing your booking. Please try your search again. If the problem continues to occur, please contact us.

Date/Time	
2018-07-10 04:56:09 PM
URL	
/
Script	
/index.html
Server	
192.168.xx.xx
IP Address	
192.168.x.xxx
Browser	
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Exception	
exception 'Exception' with message 'Make sure all files in /var/www/html/xxx/libraries/phpids/lib/IDS/tmp/default_filter.cacheare writeable!' in /var/www/html/xxx/libraries/phpids/lib/IDS/Caching/File.php:99
Stack trace:
#0 /var/www/html/xxx/libraries/phpids/lib/IDS/Caching/File.php(116): IDS_Caching_File->__construct('storage', Object(IDS_Init))
#1 [internal function]: IDS_Caching_File::getInstance('storage', Object(IDS_Init))
#2 /var/www/html/xxx/libraries/phpids/lib/IDS/Caching/Factory.php(80): call_user_func(Array, 'storage', Object(IDS_Init))
#3 /var/www/html/xxx/libraries/phpids/lib/IDS/Filter/Storage.php(106): IDS_Caching::factory(Object(IDS_Init), 'storage')
#4 /var/www/html/xxx/libraries/phpids/lib/IDS/Monitor.php(189): IDS_Filter_Storage->__construct(Object(IDS_Init))
#5 /var/www/html/xxx/libraries/ids.php(33): IDS_Monitor->__construct(Array, Object(IDS_Init))
#6 /var/www/html/xxx/index.html(30): include_once('/var/www/html/e...')
#7 {main}

**Comment by Omegatcu** [comment]
This Project isn't maintained since 2014, I wouldn't count on getting help for your problem at this time.

**Comment by swen100** [comment]
In my opinion this problem is not caused by PHPIDS, it depends on a problem between a file transfer between your Mac and Linux-Server. Please take a deeper look at your ftp-configuration.
Which ftp-program are you using?

**Comment by skyvondave** [comment]
I'm using FileZilla, and I just log in with root, as our previous developers did.

There's nothing in the FileZilla settings about overwriting permissions or ownership, but I haven't had that issue happen before anyways, as these are pre-existing files on the destination box, and I'm just copying over my edits through SFTP.

Also I don't know how these files being copied over with ownership changing would modify the default_filter.cache owner/group when the PHP files are being run; the user running the edited files is lighttpd, so if the primary .php file is root/root, is PHPIDS recreating the cache file with the primary .php file's user/group then failing to write to it?! That doesn't make any sense, I'm not sure what's going on here.

**Comment by skyvondave** [comment]
I noticed if I run `git reset --hard` in our repo, the `default_filter.cache` file changes user/group to root and permissions to -rwxr-xr-x... which then throws the exception.

I'm afraid of "fixing" this on local/sandbox then having a pull or reset or clone blow up the site for all of our customers... and I honestly am not sure if this is a PHPIDS issue (or if I need to review the correct documentation page) or a git config issue, because I was dropped into this codebase with no previous experience with PHPIDS.

Can anyone advise?
